[package]
name = "egraph-wasm-adapter"
version = "0.2.0"
authors = ["Yosuke Onoue <onoue@likr-lab.com>"]
edition = "2018"

[dependencies]
egraph-adapter = { path = "../adapter" }
js-sys = "0.3.5"
serde = "1.0.91"
serde_derive = "1.0.91"
wasm-bindgen = "0.2.45"
