[workspace]
members = [
    "crates/adapter/adapter",
    "crates/adapter/petgraph",
    "crates/adapter/wasm",
    "crates/algorithm/planarity-test",
    "crates/algorithm/biconnected-components",
    "crates/algorithm/connected-components",
    "crates/edge-bundling/fdeb",
    "crates/egraph",
    "crates/egraph-py",
    "crates/layout/fm3",
    "crates/layout/force-simulation",
    "crates/layout/grouped-force",
    "crates/quadtree",
    "crates/treemap",
    "crates/wasm",
]
