[workspace]
members = [
    "adapter/petgraph",
    "adapter/wasm",
    "clp",
    "clp-sys",
    "egraph",
    "egraph-c-api",
    "egraph-layered",
    "egraph-py",
    "egraph-wasm",
    "wasm/layout-force-directed",
]
