[workspace]
members = [
    "crates/adapter/adapter",
    "crates/adapter/petgraph",
    "crates/adapter/wasm",
    "crates/algorithm/biconnected-components",
    "crates/egraph",
    "crates/egraph-py",
    "crates/quadtree",
    "crates/treemap",
    "crates/wasm",
]
