[workspace]
members = [
    "crates/algorithm/planarity-test",
    "crates/algorithm/biconnected-components",
    "crates/algorithm/connected-components",
    "crates/algorithm/shortest-path",
    "crates/edge-bundling/fdeb",
    "crates/layout/fm3",
    "crates/layout/force",
    "crates/layout/force-simulation",
    "crates/layout/fruchterman-reingold",
    "crates/layout/grouped-force",
    "crates/layout/kamada-kawai",
    "crates/layout/non-euclidean-force-simulation",
    "crates/layout/stress-majorization",
    "crates/quadtree",
    "crates/treemap",
    "crates/util/force_derive",
    "crates/wasm",
]
