[workspace]
members = [
    "crates/adapter/petgraph",
    "crates/adapter/wasm",
    "crates/egraph",
    "crates/egraph-layered",
    "crates/egraph-py",
    "crates/wasm/grouping",
    "crates/wasm/layout-force-directed",
]
