[package]
name = "force_derive"
version = "0.1.0"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
petgraph-layout-force-simulation = { path = "../../layout/force-simulation" }
quote = "1.0.2"
syn = { version = "1.0.14", features = ["full", "extra-traits"] }
