[package]
name = "petgraph-linalg-rdmds"
version = "0.1.0"
edition = "2024"

[dependencies]
ndarray = "0.16"
num-traits = "0.2"
petgraph = "0.6"
petgraph-drawing = { path = "../../drawing" }
rand = "0.8"
