[package]
name = "egraph-c-api"
version = "0.1.0"
authors = ["Yosuke Onoue <onoue@likr-lab.com>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
clp = { path = "../clp" }
egraph-force-directed = { path = "../egraph-force-directed" }
