[package]
name = "egraph-c-api"
version = "0.1.0"
authors = ["Yosuke Onoue <onoue@likr-lab.com>"]

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
clp = { path = "../clp" }
egraph = { path = "../egraph" }
petgraph = "0.4"
