[package]
name = "petgraph-layout-ts-net"
version = "0.1.0"
edition = "2021"
authors = ["Yosuke Onoue <onoue@likr-lab.com>"]
license = "MIT"
description = "tsNET graph layout algorithm using t-SNE objective function optimization"
repository = "https://github.com/likr/egraph-rs"

[dependencies]
ndarray = "0.16"
num-traits = "0.2"
petgraph = "0.8"
petgraph-drawing = { path = "../../drawing" }
petgraph-linalg-kernel = { path = "../../linalg/kernel" }
rand = "0.8"

[dev-dependencies]
petgraph-algorithm-shortest-path = { path = "../../algorithm/shortest-path" }
