[package]
name = "egraph-force-directed"
version = "0.1.0"
authors = ["Yosuke Onoue <onoue@likr-lab.com>"]

[dependencies]

[dev-dependencies]
rand = "0.3"
getopts = "0.2"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
