[package]
name = "petgraph-layout-sgd"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = "0.16"
num-traits = "0.2"
ordered-float = "3.0"
petgraph = "0.8"
petgraph-algorithm-shortest-path = { path = "../../algorithm/shortest-path" }
petgraph-drawing = { path = "../../drawing" }
petgraph-linalg-kernel = { path = "../../linalg/kernel" }
rand = "0.8"
