[package]
name = "egraph-petgraph-adapter"
version = "0.2.0"
authors = ["Yosuke Onoue <onoue@likr-lab.com>"]
edition = "2018"

[dependencies]
egraph-adapter = { path = "../adapter" }
petgraph = "0.5"
