[package]
name = "petgraph-linalg-embedding-kernel"
version = "0.1.0"
edition = "2021"
authors = ["Yosuke Onoue <onoue@likr-lab.com>"]
license = "MIT"
description = "Kernel calculation based on coordinate embeddings"
repository = "https://github.com/likr/egraph-rs"

[dependencies]
ndarray = "0.16"
num-traits = "0.2"
petgraph = "0.8"
petgraph-drawing = { path = "../../drawing" }
petgraph-distance = { path = "../distance" }
