[package]
name = "petgraph-layout-fruchterman-reingold"
version = "0.1.0"
edition = "2018"

[dependencies]
force_derive = { path = "../../util/force_derive" }
petgraph = "0.5"
petgraph-layout-force-simulation = { path = "../force-simulation" }