[package]
name = "petgraph-layout-omega"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = "0.15"
petgraph = "0.6"
petgraph-drawing = { path = "../../drawing" }
petgraph-layout-sgd = { path = "../sgd" }
rand = "0.8"
