[package]
name = "petgraph-layout-non-euclidean-force-simulation"
version = "0.1.0"
edition = "2018"

[dependencies]
"petgraph" = "0.5"
"petgraph-layout-force-simulation" = { path = "../force-simulation" }
