[package]
name = "egraph-wasm"
version = "4.0.1-alpha.4"
authors = ["Yosuke Onoue <onoue@likr-lab.com>"]
edition = "2018"
description = "WebAssembly binding of egraph."
repository = "https://github.com/likr/egraph-rs/tree/master/crates/wasm"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
egraph = { path = "../egraph" }
egraph-wasm-adapter = { path = "../adapter/wasm" }
js-sys = "0.3.24"
serde = "1.0.91"
serde_derive = "1.0.91"

[dependencies.wasm-bindgen]
version = "0.2.48"
features = ["serde-serialize"]
