[package]
name = "egraph-wasm"
version = "5.0.0"
authors = ["Yosuke Onoue <onoue@likr-lab.com>"]
edition = "2018"
description = "WebAssembly binding of egraph."
repository = "https://github.com/likr/egraph-rs/tree/master/crates/wasm"
license = "MIT"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
js-sys = "0.3"
petgraph = "0.5"
petgraph-edge-bundling-fdeb = { path = "../edge-bundling/fdeb" }
petgraph-layout-fm3 = { path = "../layout/fm3" }
petgraph-layout-force-simulation = { path = "../layout/force-simulation" }
petgraph-layout-grouped-force = { path = "../layout/grouped-force" }
petgraph-layout-kamada-kawai = { path = "../layout/kamada-kawai" }
serde = "1.0"
serde_derive = "1.0"

[dependencies.wasm-bindgen]
version = "0.2.67"
features = ["serde-serialize"]

[dev-dependencies]
wasm-bindgen-test = "0.3.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"