[package]
name = "petgraph-clustering"
version = "0.1.0"
edition = "2024"

[dependencies]
petgraph = "0.6"
petgraph-linalg-rdmds = { path = "../linalg/rdmds" }
petgraph-drawing = { path = "../drawing" }
ndarray = "0.16"
rand = "0.8"
linfa = "0.8"
linfa-clustering = "0.8"
